#spring.application.name=produce-api
#sqs_url="${sqs_fila_pedidos_url}"
#AWS_REGION="${aws_region}"

spring.application.name=produce-api
server.port=8080

# Configurações de credenciais locais (LocalStack aceita qualquer valor)
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

# 🟢 DESVIA OS SERVIÇOS DO PRODUCER PARA O DOCKER
spring.cloud.aws.dynamodb.endpoint=http://localhost:4566
spring.cloud.aws.sqs.endpoint=http://localhost:4566

# Sua variável customizada do SQS
sqs_url=http://localhost:4566/000000000000/fila-pedidos
