#spring.application.name=worker-api
#sqs_url="${sqs_fila_pedidos_url}"
#topic_arn="${sns_topic_arn}"

spring.application.name=worker-api
server.port= 8081

# Configurações de credenciais locais
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

# 🟢 DESVIA OS SERVIÇOS DO WORKER PARA O DOCKER
spring.cloud.aws.dynamodb.endpoint=http://localhost:4566
spring.cloud.aws.sqs.endpoint=http://localhost:4566
spring.cloud.aws.sns.endpoint=http://localhost:4566

# Suas variáveis customizadas do Worker
sqs_url=http://localhost:4566/000000000000/fila-pedidos
topic_arn=arn:aws:sns:us-east-1:000000000000:notificacao-pipeline
